### PR TITLE
Renamed Folder pages to screen

### PR DESCRIPTION
**Pull request by EbhomenyeEmmanuel**
I fixed an existing issue by renaming Folder pages to screen.

### CODE REVIEW

**Review by priyanshu-01 — APPROVED** [review]

**Comment by aryamangodara** [comment]
label it as spam @priyanshu-01 ,

**Comment by EbhomenyeEmmanuel** [comment]
Why? @aryamangodara

**Comment by aryamangodara** [comment]
> Why? @aryamangodara

cause you have changed the folder name but didn't changed the imports
which means you have not even have run the project on your system

**Comment by EbhomenyeEmmanuel** [comment]
The imports were used in main.dart. All the files there has the right import name which is "./pages/". Inspect the code before you give a bad suggestion. @aryamangodara

**Comment by aryamangodara** [comment]
@EbhomenyeEmmanuel  are you cracked or what , thats what I am saying ./pages was present but then you have to change it to ./screens. People like  just come here for t-shirts , think themselves as "ELUN MOUSIK"(Elon Musk)

**Comment by EbhomenyeEmmanuel** [comment]
Oh, my bad.

**Pull request merged**
